# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cron_info',
            name='cron_idnumber',
        ),
        migrations.AlterField(
            model_name='cron_info',
            name='cron_cmd',
            field=models.CharField(default='222', max_length=512, verbose_name='\u547d\u4ee4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cron_info',
            name='cron_rule',
            field=models.CharField(default='sdf', max_length=50, verbose_name='\u65f6\u95f4\u89c4\u5219'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cron_info',
            name='cron_service_ip',
            field=models.GenericIPAddressField(default=1, verbose_name='\u8fd0\u884c\u7684\u670d\u52a1\u5668IP'),
            preserve_default=False,
        ),
    ]
