# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronmanager', '0002_auto_20170524_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cron_info',
            old_name='corn_name',
            new_name='cron_name',
        ),
    ]
