# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronmanager', '0003_auto_20170524_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cron_info',
            options={},
        ),
    ]
