# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronmanager', '0004_auto_20170524_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cron_info',
            options={'verbose_name': '\u4efb\u52a1\u7ba1\u7406', 'verbose_name_plural': '\u4efb\u52a1\u7ba1\u7406'},
        ),
    ]
