# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronmanager', '0005_auto_20170524_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron_info',
            name='cron_name',
            field=models.CharField(max_length=100, verbose_name='\u4efb\u52a1\u540d'),
        ),
        migrations.AlterField(
            model_name='cron_info',
            name='cron_status',
            field=models.CharField(choices=[('stop', '\u7981\u7528'), ('run', '\u542f\u7528')], default='stop', max_length=32, verbose_name='\u72b6\u6001'),
        ),
    ]
