# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronmanager', '0006_auto_20170524_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cron_info',
            name='cron_status',
        ),
    ]
