# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronmanager', '0007_remove_cron_info_cron_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cron_info',
            name='cron_status',
            field=models.CharField(choices=[('stop', '\u7981\u7528'), ('run', '\u542f\u7528')], default='stop', max_length=32, verbose_name='\u72b6\u6001'),
        ),
    ]
