# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronmanager', '0008_cron_info_cron_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cron_info',
            options={},
        ),
        migrations.RemoveField(
            model_name='cron_info',
            name='crom_memo',
        ),
        migrations.RemoveField(
            model_name='cron_info',
            name='cron_cmd',
        ),
        migrations.RemoveField(
            model_name='cron_info',
            name='cron_owner',
        ),
        migrations.RemoveField(
            model_name='cron_info',
            name='cron_rule',
        ),
        migrations.RemoveField(
            model_name='cron_info',
            name='cron_service_ip',
        ),
        migrations.RemoveField(
            model_name='cron_info',
            name='cron_status',
        ),
    ]
