# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronmanager', '0010_auto_20170524_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cron_info',
        ),
    ]
