# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hostgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_groupname', models.CharField(max_length=30)),
                ('create_date', models.CharField(max_length=30)),
                ('create_user', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=30)),
                ('host_user', models.CharField(max_length=30)),
                ('host_pass', models.CharField(max_length=50)),
                ('host_w_ip', models.GenericIPAddressField()),
                ('host_w_port', models.PositiveIntegerField()),
                ('host_n_ip', models.GenericIPAddressField()),
                ('host_n_port', models.PositiveIntegerField()),
                ('host_root_pwd', models.CharField(max_length=50)),
                ('script_dir', models.CharField(max_length=100)),
                ('host_description', models.TextField(blank=True)),
                ('create_user', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='scriptgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_groupname', models.CharField(max_length=30)),
                ('create_date', models.CharField(max_length=30)),
                ('create_user', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=30)),
                ('script_file', models.FileField(upload_to='aop/script/')),
                ('script_date', models.CharField(max_length=50)),
                ('script_description', models.TextField(blank=True)),
                ('create_user', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='svns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svn_name', models.CharField(max_length=20)),
                ('svn_user', models.CharField(max_length=30)),
                ('svn_pass', models.CharField(max_length=30)),
                ('svn_local', models.CharField(max_length=100)),
                ('svn_path', models.CharField(max_length=100)),
                ('create_user', models.CharField(max_length=10)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.hosts')),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_date', models.CharField(max_length=50)),
                ('task_status', models.CharField(max_length=10)),
                ('task_create_user', models.CharField(max_length=30)),
                ('host_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.hostgroup')),
                ('script_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.scriptgroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u59d3\u540d')),
                ('iphone', models.CharField(max_length=11, verbose_name='\u624b\u673a')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scriptgroup',
            name='script',
            field=models.ManyToManyField(to='app01.scripts'),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='host',
            field=models.ManyToManyField(to='app01.hosts'),
        ),
    ]
