# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shost', models.CharField(max_length=100)),
                ('sdir', models.CharField(max_length=100)),
                ('ddir', models.CharField(max_length=100)),
                ('dhost', models.ManyToManyField(to='app01.hosts')),
            ],
        ),
    ]
