# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='shost',
            field=models.GenericIPAddressField(),
        ),
    ]
