# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170308_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='shost',
            field=models.GenericIPAddressField(verbose_name='\u9884\u53d1\u5e03\u673a'),
        ),
    ]
