# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170308_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='cmdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('MAC', models.CharField(max_length=50, verbose_name='MAC\u5730\u5740')),
                ('ServerType', models.CharField(max_length=50, verbose_name='\u8d44\u4ea7\u578b\u53f7')),
                ('ServerSN', models.CharField(max_length=50, verbose_name='\u8d44\u4ea7SN')),
                ('Disk', models.CharField(max_length=50, verbose_name='\u786c\u76d8\u5bb9\u91cf\u8f6c\u901f')),
                ('DiskSN', models.CharField(max_length=50, verbose_name='\u786c\u76d8\u5e8f\u5217\u53f7')),
                ('Mem', models.CharField(max_length=50, verbose_name='\u5185\u5b58')),
                ('CPU', models.CharField(max_length=100)),
                ('iDracIP', models.GenericIPAddressField()),
                ('ServerName', models.ManyToManyField(to='app01.hosts')),
            ],
        ),
    ]
