# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_cmdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdb',
            name='AssetName',
            field=models.CharField(default=1, max_length=100, verbose_name='\u8d44\u4ea7\u540d'),
            preserve_default=False,
        ),
    ]
