# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_cmdb_assetname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='CPU',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='Disk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u786c\u76d8\u5bb9\u91cf\u8f6c\u901f'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='DiskSN',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u786c\u76d8\u5e8f\u5217\u53f7'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='IP',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='MAC',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='Mem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='iDracIP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
