# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_online_sexcludedir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='host_pass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='host_root_pwd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
