# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmdb',
            name='AssetName',
        ),
        migrations.AddField(
            model_name='cmdb',
            name='AssetSn',
            field=models.CharField(default='aaaa', max_length=50, verbose_name='\u8d44\u4ea7\u7f16\u53f7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmdb',
            name='AssetType',
            field=models.CharField(default='111', max_length=100, verbose_name='\u8d44\u4ea7\u7c7b\u578b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmdb',
            name='Memo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='RaidInfo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raid\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='Disk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u786c\u76d8'),
        ),
        migrations.RemoveField(
            model_name='cmdb',
            name='ServerName',
        ),
        migrations.AddField(
            model_name='cmdb',
            name='ServerName',
            field=models.CharField(default='1111', max_length=100, verbose_name='\u8d44\u4ea7\u540d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='iDracIP',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7ba1\u7406IP'),
        ),
    ]
