# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app01', '0011_auto_20170426_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='svn_permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_info', models.CharField(max_length=100)),
                ('svn_projects', models.ManyToManyField(to='app01.svns')),
                ('web_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SVN\u6743\u9650\u8868',
                'verbose_name_plural': 'SVN\u6743\u9650\u8868',
            },
        ),
    ]
