# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20170428_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online_permission',
            name='src_dir',
            field=models.TextField(),
        ),
    ]
