# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7aef\u53e3')),
                ('service_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u670d\u52a1\u540d')),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='manufactory',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='parent_unit',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='disk',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='disk',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='firmware',
        ),
        migrations.DeleteModel(
            name='NewAssetApprovalZone',
        ),
        migrations.AlterUniqueTogether(
            name='nic',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='nic',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='raidadaptor',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='raidadaptor',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ram',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='securitydevice',
            name='asset',
        ),
        migrations.AlterModelOptions(
            name='server',
            options={},
        ),
        migrations.RemoveField(
            model_name='server',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='server',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='server',
            name='hosted_on',
        ),
        migrations.RemoveField(
            model_name='server',
            name='model',
        ),
        migrations.RemoveField(
            model_name='server',
            name='os_distribution',
        ),
        migrations.RemoveField(
            model_name='server',
            name='os_release',
        ),
        migrations.RemoveField(
            model_name='server',
            name='os_type',
        ),
        migrations.RemoveField(
            model_name='server',
            name='raid_type',
        ),
        migrations.RemoveField(
            model_name='server',
            name='sub_asset_type',
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_cores',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU\u6838\u6570'),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU\u4e2a\u6570'),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CPU\u578b\u53f7'),
        ),
        migrations.AddField(
            model_name='server',
            name='disk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u78c1\u76d8'),
        ),
        migrations.AddField(
            model_name='server',
            name='ex_ip',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5916\u7f51IP'),
        ),
        migrations.AddField(
            model_name='server',
            name='host_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e3b\u673a\u540d'),
        ),
        migrations.AddField(
            model_name='server',
            name='in_ip',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='\u5185\u7f51IP'),
        ),
        migrations.AddField(
            model_name='server',
            name='max_open_files',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6700\u5927\u6253\u5f00\u6587\u4ef6\u6570'),
        ),
        migrations.AddField(
            model_name='server',
            name='mem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5185\u5b58'),
        ),
        migrations.AddField(
            model_name='server',
            name='os_kernel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7cfb\u7edf\u5185\u6838'),
        ),
        migrations.AddField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c'),
        ),
        migrations.AddField(
            model_name='server',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f4d\u7f6e'),
        ),
        migrations.AddField(
            model_name='server',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.NullBooleanField(default=False, verbose_name='\u8fd0\u884c\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='server',
            name='uptime',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5728\u7ebf\u65f6\u95f4\uff08\u5929\uff09'),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
        migrations.DeleteModel(
            name='IDC',
        ),
        migrations.DeleteModel(
            name='Manufactory',
        ),
        migrations.DeleteModel(
            name='NetworkDevice',
        ),
        migrations.DeleteModel(
            name='NIC',
        ),
        migrations.DeleteModel(
            name='RaidAdaptor',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.DeleteModel(
            name='SecurityDevice',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='service',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Server', verbose_name='\u670d\u52a1\u5668'),
        ),
    ]
