# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron_info',
            name='cron_status',
            field=models.CharField(choices=[('stop', '\u7981\u7528'), ('running', '\u542f\u7528')], default='stop', max_length=32, verbose_name='\u72b6\u6001'),
        ),
    ]
