# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronapp', '0002_auto_20170526_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='cron_info',
            name='cron_run_user',
            field=models.CharField(default=1, max_length=20, verbose_name='\u8fd0\u884c\u8005'),
            preserve_default=False,
        ),
    ]
